{{- if .Values.adminApp.enabled }}
apiVersion: app.sealos.io/v1
kind: App
metadata:
  name: aiproxy-admin
  namespace: app-system
spec:
  data:
    desc: Sealos AI Proxy 管理端
    url: {{ include "aiproxy.backendExternalURL" . | quote }}
  displayType: {{ .Values.adminApp.displayType | quote }}
  i18n:
    zh:
      name: AI Proxy 管理端
    zh-Hans:
      name: AI Proxy 管理端
  icon: {{ printf "%s/logo.svg" (include "aiproxy.backendExternalURL" .) | quote }}
  name: Sealos AI Proxy Admin
  type: iframe
{{- end }}
