apiVersion: app.sealos.io/v1
kind: App
metadata:
  name: aiproxy
  namespace: app-system
spec:
  data:
    desc: Sealos AI Proxy
    url: {{ printf "%s%s" (include "aiproxy.webExternalURL" .) (default "" .Values.suffix) | quote }}
  displayType: more
  i18n:
    zh:
      name: AI Proxy
    zh-Hans:
      name: AI Proxy
  icon: {{ printf "%s/logo.svg" (include "aiproxy.webExternalURL" .) | quote }}
  name: AI Proxy
  type: iframe
