apiVersion: v1
data:
  AI_PROXY_BACKEND_KEY: "{{.Values.aiproxy.AI_PROXY_BACKEND_KEY}}"
  APP_TOKEN_JWT_KEY: "{{.Values.aiproxy.APP_TOKEN_JWT_KEY}}"
  CURRENCY_SYMBOL: "{{.Values.aiproxy.CURRENCY_SYMBOL}}"
  NODE_TLS_REJECT_UNAUTHORIZED: "{{.Values.aiproxy.NODE_TLS_REJECT_UNAUTHORIZED}}"
  AI_PROXY_BACKEND: {{ include "aiproxy.backendExternalURL" . | quote }}
  AI_PROXY_BACKEND_INTERNAL: "http://aiproxy.{{.Release.Namespace}}.svc:3000"
  ADMIN_NAMESPACES: "{{.Values.aiproxy.ADMIN_NAMESPACES}}"
  IS_INVITATION_ACTIVE: "{{.Values.aiproxy.IS_INVITATION_ACTIVE}}"
  DOC_URL: "{{.Values.aiproxy.DOC_URL}}"
  {{- if ne .Values.aiproxy.CURRENCY_SYMBOL "usd" }}
  ACCOUNT_SERVER: "{{.Values.aiproxy.ACCOUNT_SERVER}}"
  ACCOUNT_SERVER_TOKEN_JWT_KEY: "{{.Values.aiproxy.ACCOUNT_SERVER_TOKEN_JWT_KEY}}"
  {{- end }}
kind: ConfigMap
metadata:
  namespace: {{.Release.Namespace}}
  name: {{ include "aiproxy.fullname" . }}
  labels:
    {{- include "aiproxy.labels" . | nindent 4 }}
